name: Build and publish to private Maven repo

on:
  push:
    branches: [ master, release-* ]
    paths-ignore:
      - 'js/**'
  pull_request:
    branches: [ master, release-* ]
    paths-ignore:
      - 'js/**'

env:
  DISPLAY: ':0'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - id: setupJava
        name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Adjust Maven toolchains.xml
        run: |
          cd ~/.m2/
          mv toolchains.xml toolchains.xml.bak
          sed 's@<version>8</version>@<version>1.8</version>@' <toolchains.xml.bak >toolchains.xml

      - name: Install virtual frame buffer
        run: |
          sudo apt-get -q update
          sudo apt-get -qy install xvfb libxtst6 libxi-dev

      - name: Start virtual frame buffer
        run: |
          echo Xvfb ${DISPLAY} +extension GLX -screen 0 1024x768x24
          Xvfb ${DISPLAY} +extension GLX -screen 0 1024x768x24 & sleep 3s
          echo Should be running now

      - name: Build and deploy with Maven
        run: |
          if [ "${{ github.event_name }}" == "push" ]
          then
            mvn -B -s settings.xml deploy -Pjogl1 -Pwebstart -Ddependency-check.skip
          else
            mvn -B -s settings.xml verify -Pjogl1 -Pwebstart -Ddependency-check.skip
          fi
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_IVENZA_NET_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_IVENZA_NET_PASSWORD }}

      - name: Stop virtual frame buffer
        uses: bcomnes/cleanup-xvfb@v1

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-report/target/site/jacoco-aggregate
